# Generated by Django 4.2.7 on 2026-08-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('check_interval', models.IntegerField(default=300)),
                ('timeout', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN'), ('unknown', 'UNKNOWN')], default='unknown', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN'), ('timeout', 'TIMEOUT'), ('error', 'ERROR')], max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.service')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['service', '-checked_at'], name='monitor_che_service_246065_idx')],
            },
        ),
    ]
